/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#define SRAM_SATRT 0x20000000U
#define SRAM_SIZE (128*1024)
#define SRAM_END  ((SRAM_SATRT) + (SRAM_SIZE))
#define STACK_START SRAM_END

#define STACK_MSP_START  STACK_START
#define STACK_MSP_END    (STACK_START + 512)
#define STACK_PSP_START  STACK_MSP_END

void generate_exception(void){
	__asm volatile("SVC #0x2");
}

__attribute__((naked)) void change_sp_to_psp(void)
{
    __asm volatile(
        ".equ SRAM_END, (0x20000000 + (128 * 1024))      \n"
        ".equ PSP_START, (SRAM_END - 512)                \n"
        "LDR R0, =PSP_START                              \n"
        "MSR PSP, R0                                     \n"
        "MOV R0, #0x02                                   \n"
        "MSR CONTROL, R0                                 \n"
        "BX LR                                           \n"
    );
}

int fun_add(int a, int b, int c, int d){
	return (a + b + c + d);
}

int main(void)
{
	change_sp_to_psp();
	int ret;

	ret = fun_add(1, 4, 5,6);

	printf("Result : %d\n", ret);

	for(;;);
}
