/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/**
 ******************************************************************************
 * @file    syscalls.c
 * @brief   Minimal newlib syscalls implementation using ITM (SWO)
 * @author  voidEmbedded
 ******************************************************************************
 */

#include <stdint.h>
#include <stddef.h>
#include <errno.h>
#include <sys/stat.h>
#include <sys/times.h>

/* -------------------------------------------------------------------------- */
/*   ITM Register Definitions                                                 */
/* -------------------------------------------------------------------------- */
#define DEMCR               (*((volatile uint32_t *)0xE000EDFCU))
#define ITM_STIMULUS_PORT0  (*((volatile uint32_t *)0xE0000000U))
#define ITM_TRACE_EN        (*((volatile uint32_t *)0xE0000E00U))

/* -------------------------------------------------------------------------- */
/*   Function Prototypes                                                      */
/* -------------------------------------------------------------------------- */
void ITM_SendChar(uint8_t ch);
int __io_putchar(int ch);
int __io_getchar(void);

/* -------------------------------------------------------------------------- */
/*   ITM Send Function                                                        */
/* -------------------------------------------------------------------------- */
void ITM_SendChar(uint8_t ch)
{
    /* Enable TRCENA (bit 24 in DEMCR) */
    DEMCR |= (1 << 24);

    /* Enable stimulus port 0 */
    ITM_TRACE_EN |= (1 << 0);

    /* Wait for ITM port to be ready */
    while (!(ITM_STIMULUS_PORT0 & 1))
        ;

    /* Write the character to port 0 */
    ITM_STIMULUS_PORT0 = ch;
}

/* -------------------------------------------------------------------------- */
/*   I/O Redirection                                                          */
/* -------------------------------------------------------------------------- */

/* printf() redirection */
int __io_putchar(int ch)
{
    ITM_SendChar((uint8_t)ch);
    return ch;
}

/* scanf() redirection (ITM has no input) */
int __io_getchar(void)
{
    /* No input support for ITM; return EOF */
    return -1;
}

/* -------------------------------------------------------------------------- */
/*   Standard System Call Stubs                                               */
/* -------------------------------------------------------------------------- */

char *__env[1] = {0};
char **environ = __env;

void initialise_monitor_handles(void) {}

/* Process and file-related stubs */
int _getpid(void) { return 1; }

int _kill(int pid, int sig)
{
    (void)pid;
    (void)sig;
    errno = EINVAL;
    return -1;
}

void _exit(int status)
{
    _kill(status, -1);
    while (1)
        ;
}

__attribute__((weak)) int _write(int file, char *ptr, int len)
{
    (void)file;
    for (int i = 0; i < len; i++)
    {
        __io_putchar(*ptr++);
    }
    return len;
}

__attribute__((weak)) int _read(int file, char *ptr, int len)
{
    (void)file;
    int i;
    int c;

    for (i = 0; i < len; i++)
    {
        c = __io_getchar();
        if (c == -1)
            return i; // No more data
        *ptr++ = (char)c;
    }

    return len;
}

int _close(int file) { (void)file; return -1; }

int _fstat(int file, struct stat *st)
{
    (void)file;
    st->st_mode = S_IFCHR;
    return 0;
}

int _isatty(int file) { (void)file; return 1; }

int _lseek(int file, int ptr, int dir)
{
    (void)file;
    (void)ptr;
    (void)dir;
    return 0;
}

int _open(char *path, int flags, ...)
{
    (void)path;
    (void)flags;
    return -1;
}

int _wait(int *status)
{
    (void)status;
    errno = ECHILD;
    return -1;
}

int _unlink(char *name)
{
    (void)name;
    errno = ENOENT;
    return -1;
}

int _times(struct tms *buf)
{
    (void)buf;
    return -1;
}

int _stat(char *file, struct stat *st)
{
    (void)file;
    st->st_mode = S_IFCHR;
    return 0;
}

int _link(char *old, char *new)
{
    (void)old;
    (void)new;
    errno = EMLINK;
    return -1;
}

int _fork(void)
{
    errno = EAGAIN;
    return -1;
}

int _execve(char *name, char **argv, char **env)
{
    (void)name;
    (void)argv;
    (void)env;
    errno = ENOMEM;
    return -1;
}
