/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Write a program o execute an SVC instructio from thread mode,
 *                   Implement the SVC handler to print the SVC number used.
 *                   Also, increment the SVC number by 4 and return it to the thread mode code and print it
 *
 *                   Hints:
 *                   1. Write a main() function where you should execute the SVC instruction with an arguments
 *                   2. Implement the SVC handler extract the SVC number and print it using printf
 *                   3. In the SVC handler extract the SVC number and print it using printf
 *                   4. Increment the SVC number by 4 and return is to the thread mode
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

/* Thread mode code */
int main(void)
{
    __asm volatile ("SVC #25");
    register uint32_t data __asm("r0");
    printf(" data = %ld\n", data);
    while (1);
}

/* Naked SVC handler (ASM wrapper) */
__attribute__((naked)) void SVC_Handler(void)
{
    __asm volatile (
        "TST lr, #4        \n"  // Test EXC_RETURN bit 2
        "ITE EQ            \n"
        "MRSEQ r0, MSP     \n"  // If 0, use MSP
        "MRSNE r0, PSP     \n"  // If 1, use PSP
        "B SVC_Handler_C   \n"
    );
}

/* C part of SVC handler */
void SVC_Handler_C(uint32_t *pBaseOfStackFrame)
{
    printf("In the SVC handler\r\n");

    /* PC is at index 6 in stack frame */
    uint8_t *pReturnAddr = (uint8_t *)pBaseOfStackFrame[6];

    /* SVC instruction is 2 bytes before PC */
    uint8_t svc_number = pReturnAddr[-2];

    printf("SVC number = %d\r\n", svc_number);
}
