/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 *
 ******************************************************************************
 */

#define IRQNO_TIM6     54
#define IRQNO_UART3   39
#define IRQNO_OTG_FS  77

#define NVIC_IPR_BASE   ((uint32_t*)0xE000E400)
#define NVIC_ISER_BASE  ((uint32_t*)0xE000E100)
#define NVIC_ISPR_BASE  ((uint32_t*)0xE000E200)

void configure_priority_for_irq(uint8_t irq_no, uint8_t priority)
{
    uint8_t iprx = irq_no / 4;
    uint8_t pos  = (irq_no % 4) * 8;
    NVIC_IPR_BASE[iprx] &= ~(0xFF << pos);
    NVIC_IPR_BASE[iprx] |= (priority << pos);
}

void enable_irq(uint8_t irq_no)
{
    NVIC_ISER_BASE[irq_no / 32] |= (1 << (irq_no % 32));
}

void set_pending_irq(uint8_t irq_no)
{
    NVIC_ISPR_BASE[irq_no / 32] |= (1 << (irq_no % 32));
}


void TIM6_DAC_IRQHandler(void)
{
    printf(">>> Enter TIM6 ISR (P=0x80)\n");

    // Trigger higher priority IRQ
    set_pending_irq(IRQNO_UART3);

    printf("<<< Exit TIM6 ISR\n");
}

void USART3_IRQHandler(void)
{
    printf(">>> Enter UART3 ISR (P=0x60)\n");

    // Trigger lower priority IRQ
    set_pending_irq(IRQNO_OTG_FS);

    printf("<<< Exit UART3 ISR\n");
}

void OTG_FS_IRQHandler(void)
{
    printf(">>> Enter OTG FS ISR\n");
    printf("<<< Exit OTG FS ISR\n");
}


int main(void)
{
    // Task-2 priorities
    configure_priority_for_irq(IRQNO_TIM6,   0x80);
    configure_priority_for_irq(IRQNO_UART3,  0x60);
    configure_priority_for_irq(IRQNO_OTG_FS, 0x70);

    enable_irq(IRQNO_TIM6);
    enable_irq(IRQNO_UART3);
    enable_irq(IRQNO_OTG_FS);

    // Start with TIM6
    set_pending_irq(IRQNO_TIM6);

    while(1);
}

