/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
#include <stdio.h>

#define IRQNO_TIMER2 28
#define IRQNO_I2C1 31

#define NVIC_IPR_BASE  ((uint32_t*)0xE000E400)
#define NVIC_ISER_BASE ((uint32_t*)0xE000E100)
#define NVIC_ISPR_BASE ((uint32_t*)0xE000E200)

// Function to configure priority
void configure_priority_for_irqs(uint8_t irq_no, uint8_t priority_value){
    uint8_t iprx = irq_no / 4;       // Each IPR register holds 4 IRQs
    uint8_t pos  = (irq_no % 4) * 8; // Each IRQ uses 8 bits

    uint32_t *ipr = NVIC_IPR_BASE + iprx;

    *ipr &= ~(0xFF << pos);          // Clear old priority
    *ipr |= ((priority_value & 0xFF) << pos); // Set new priority
}

// Function to enable IRQ
void enable_irq(uint8_t irq_no){
    uint8_t reg_index = irq_no / 32;  // Select ISER/ISPR register
    uint8_t bit_pos   = irq_no % 32;  // Select bit inside register

    NVIC_ISER_BASE[reg_index] |= (1 << bit_pos);
}

// Function to set pending IRQ
void set_pending_irq(uint8_t irq_no){
    uint8_t reg_index = irq_no / 32;
    uint8_t bit_pos   = irq_no % 32;

    NVIC_ISPR_BASE[reg_index] |= (1 << bit_pos);
}

// ----------------- MAIN -----------------
int main(void)
{
    // 1. Configure priorities
    configure_priority_for_irqs(IRQNO_TIMER2, 0x80); // Lower 4 bits used in STM32F4
    configure_priority_for_irqs(IRQNO_I2C1, 0x90);

    // 2. Set pending bit for TIMER2 (simulate IRQ)
    set_pending_irq(IRQNO_TIMER2);

    // 3. Enable IRQs
    enable_irq(IRQNO_TIMER2);
    enable_irq(IRQNO_I2C1);

    printf("NVIC configured. Pending IRQ set.\n");

    // In real MCU, ISRs are called automatically by NVIC
    return 0;
}

// ----------------- ISR -----------------
void TIM2_IRQHandler(void){
    printf("TIM2 ISR executed\n");

    // Optionally trigger I2C1 interrupt
    set_pending_irq(IRQNO_I2C1);
}

void I2C1_EV_IRQHandler(void){
    printf("I2C1 ISR executed\n");
}
